on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\vsts-prerequisites.ps1
      shell: powershell
    - name: Build
      id: buildmodule
      run: .\build\vsts-build.ps1 -LocalRepo -SkipPublish
      shell: powershell
    - uses: actions/upload-artifact@v3
      with:
        name: module
        path: publish/cScom
    - name: Validate
      run: .\build\vsts-validate.ps1
      shell: powershell
    - name: Publish
      run: .\build\vsts-build.ps1 -ApiKey $env:APIKEY
      shell: powershell
      env:
        APIKEY: ${{ secrets.ApiKey }}