on: [pull_request]

jobs:
  validate:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\vsts-prerequisites.ps1
      shell: powershell
    - name: Build
      run: .\build\vsts-build.ps1 -LocalRepo -SkipPublish
      shell: powershell
    - uses: actions/upload-artifact@v3
      with:
        name: module
        path: publish/cScom
    - name: Validate
      run: .\build\vsts-validate.ps1
      shell: powershell